### ISSUE TITLE
EPIC – Recipe App MVP development

### ISSUE THREAD

**Issue by lauracastrotech** [chingu-voyages/v46-tier1-team-08#14]
**__Feature Description__**
The following define the minimum requirements and features that you may implement to enhance this app, if time permits.

**__Major User Stories/tasks__**
- [ ] Task 1: [Landing Page Components](https://github.com/chingu-voyages/v46-tier1-team-08/issues/15)
- [ ] Task 2: [Search Component](https://github.com/chingu-voyages/v46-tier1-team-08/issues/16)
- [ ] Task 3: [Main Data Display Component](https://github.com/chingu-voyages/v46-tier1-team-08/issues/17)
- [ ] Task 4: [Summary Detail Component](https://github.com/chingu-voyages/v46-tier1-team-08/issues/18)

Additional Considerations:
- This is a purely frontend application. No backend is required.
- You may use any languages, tools, or libraries you prefer when designing and building this app.
- We've included a JSON file containing the raw data in the /assets directory in this repo. But, if you choose, you may use the [Recipe - Rapid API](https://rapidapi.com/apidojo/api/tasty) instead.
- You may NOT use AI-base solution generators like GitHub CoPilot.

Useful links and resources:
o	[Example Recipe App](https://namka-food-api.netlify.app/)
o	[Recipe - Rapid API](https://rapidapi.com/apidojo/api/tasty)
